'use strict';
/**
 * script -- turn the research brief into beats, then write beats.js.
 *
 * One beat = one spoken sentence + the visual played while it is spoken. That
 * is the pipeline's single source of truth, so this stage's real output is the
 * file on disk, not the JSON it returns.
 */

const fs = require('fs');
const path = require('path');
const { askJson } = require('../llm-router');
const { videoDir } = require('../paths');
const { validateBeats } = require('../validate-beats');
const { composeTitle } = require('../naming');
const { ALI } = require('../characters');

const SCHEMA = {
  type: 'object',
  properties: {
    title: { type: 'string', description: 'the SUBTOPIC this video covers, max 8 words, no pipe characters — the module prefix is added automatically' },
    beats: {
      type: 'array',
      minItems: 10,
      maxItems: 22,   // hard cap; the gate is told not to ask for more than this
      items: {
        type: 'object',
        properties: {
          id: { type: 'string', description: 'two-digit, e.g. "01"' },
          vo: { type: 'string', description: 'exactly one spoken sentence' },
          mode: { type: 'string', enum: ['ali', 'scene', 'info'] },
          art: { type: 'string', description: 'art prompt; forbid text/letters/numbers' },
          overlay: { type: 'string', description: 'optional HTML overlay text' },
          // Required on info beats -- without it the beat renders as a blank frame.
          info: {
            type: 'object',
            properties: {
              tpl: {
                type: 'string',
                enum: ['checks', 'fourparts', 'gauge', 'statement', 'twocard', 'quote'],
              },
              data: { type: 'object', additionalProperties: true },
            },
            required: ['tpl', 'data'],
            additionalProperties: false,
          },
        },
        required: ['id', 'vo', 'mode'],
        additionalProperties: false,
      },
    },
  },
  required: ['title', 'beats'],
  additionalProperties: false,
};

/** Render the beats array as the beats.js module the pipeline expects. */
function renderBeatsFile(script) {
  const header = [
    '// Generated by the orchestrator spine. One beat = one spoken sentence.',
    `// Title: ${script.title}`,
    '',
    'module.exports = [',
  ];
  const body = script.beats.map((b) => {
    const fields = [
      `    id: ${JSON.stringify(b.id)}`,
      `    mode: ${JSON.stringify(b.mode)}`,
      `    vo: ${JSON.stringify(b.vo)}`,
      b.art ? `    art: ${JSON.stringify(b.art)}` : null,
      b.info ? `    info: ${JSON.stringify(b.info)}` : null,
      b.overlay ? `    overlay: ${JSON.stringify(b.overlay)}` : null,
    ].filter(Boolean).join(',\n');
    return `  {\n${fields},\n  },`;
  });
  return [...header, ...body, '];', ''].join('\n');
}

/**
 * Redraft schema: ONLY the beats that change.
 *
 * Asking for the whole script back and instructing "leave the rest identical" was
 * measured twice and does not work -- a redraft fixed 5-6 beats, left 4 unfixed,
 * and BROKE 6-7 beats nobody had complained about. The instruction is advisory and
 * the model does not comply. So the invariant is made structural instead: the
 * model returns a patch, code applies it, and an unmentioned beat cannot change
 * because nothing rewrites it.
 */
const EDIT_SCHEMA = {
  type: 'object',
  properties: {
    edits: {
      type: 'array',
      description: 'one entry per beat you are changing; omit any field you are not changing',
      items: {
        type: 'object',
        properties: {
          id: { type: 'string', description: 'the id of an EXISTING beat' },
          vo: { type: 'string' },
          mode: { type: 'string', enum: ['ali', 'scene', 'info'] },
          art: { type: 'string' },
          overlay: { type: 'string' },
          info: {
            type: 'object',
            properties: {
              tpl: { type: 'string', enum: ['checks', 'fourparts', 'gauge', 'statement', 'twocard', 'quote'] },
              data: { type: 'object', additionalProperties: true },
            },
            required: ['tpl', 'data'],
            additionalProperties: false,
          },
        },
        required: ['id'],
        additionalProperties: false,
      },
    },
    // Only when the reviewer says a MOMENT is missing, not to pad the count.
    new_beats: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          after_id: { type: 'string', description: 'insert after this existing beat id' },
          vo: { type: 'string' },
          mode: { type: 'string', enum: ['ali', 'scene', 'info'] },
          art: { type: 'string' },
          overlay: { type: 'string' },
          info: { type: 'object', additionalProperties: true },
        },
        required: ['after_id', 'vo', 'mode'],
        additionalProperties: false,
      },
    },
    removed_ids: {
      type: 'array',
      items: { type: 'string' },
      description: 'ids to delete, only if the reviewer called a beat redundant',
    },
  },
  required: ['edits'],
  additionalProperties: false,
};

/**
 * Apply a patch to the previous beats. Beats not named in the patch are carried
 * through untouched -- that is the whole point.
 * @returns {{beats: object[], touched: string[]}}
 */
function applyEdits(previous, patch) {
  const byId = new Map(previous.map((b) => [b.id, { ...b }]));
  const touched = [];

  for (const e of patch.edits || []) {
    const existing = byId.get(e.id);
    if (!existing) {
      throw new Error(`redraft edits beat '${e.id}', which does not exist in the previous draft`);
    }
    const { id, ...changes } = e;
    // Only fields actually present are overwritten; the rest stay as they were.
    for (const [k, v] of Object.entries(changes)) {
      if (v !== undefined && v !== null && v !== '') existing[k] = v;
    }
    // Switching to/from info must not leave a stale field that breaks rendering.
    if (existing.mode === 'info') delete existing.art;
    else delete existing.info;
    byId.set(e.id, existing);
    touched.push(e.id);
  }

  for (const id of patch.removed_ids || []) {
    if (byId.delete(id)) touched.push(`-${id}`);
  }

  let beats = previous.map((b) => byId.get(b.id)).filter(Boolean);
  // Include any survivors that were added in an earlier patch round.
  for (const [id, b] of byId) if (!beats.some((x) => x.id === id)) beats.push(b);

  for (const nb of patch.new_beats || []) {
    const at = beats.findIndex((b) => b.id === nb.after_id);
    const { after_id, ...beat } = nb;
    // A synthetic id that cannot collide with the two-digit ones.
    beat.id = `${nb.after_id}a`;
    if (at === -1) beats.push(beat); else beats.splice(at + 1, 0, beat);
    touched.push(`+${beat.id}`);
  }

  return { beats, touched };
}

module.exports = {
  name: 'script',
  maxAttempts: 3,

  async run({ item, artifacts, opts, log }) {
    const brief = artifacts.research;

    // A redraft round (ILHAM 3.3): the gate sent this back with a critique, so the
    // next draft must answer it rather than start from scratch and repeat itself.
    const redraft = artifacts.redraftFeedback;
    if (redraft) {
      log(`redraft round ${redraft.round}: answering ${redraft.latest.length} point(s) from the gate`);
    } else {
      log('drafting beats');
    }

    // A redraft asks for a PATCH against the previous beats, and the patch is
    // applied in code. A first draft asks for the whole script.
    const previousBeats = redraft && artifacts.script && Array.isArray(artifacts.script.beats)
      ? artifacts.script.beats
      : null;
    const patchMode = Boolean(previousBeats && previousBeats.length);

    const raw = await askJson({
      log,
      promptName: 'video_script',
      input: JSON.stringify({
        topic: item.topic,
        series: item.series,
        brief,
        // Beat budget. 28 beats came back as a 2.7-minute script (over the 1.5-2.5
        // house range) AND a ~15k-character reply that got truncated on 2 of 3
        // attempts. A tighter cap fixes the length and the fragility together.
        // Ali's look is fixed for the whole series, not chosen per video. Three
        // videos produced three different men before this was pinned. Validation
        // rejects a draft that departs from it, so it must be stated here.
        character_canon: {
          ali: ALI,
          rule: 'Every art prompt showing Ali must include this description verbatim. '
            + 'Vary his pose, expression and props freely; never his age, hair, skin or clothing.',
        },
        length_requirement: {
          beats_min: 16,
          beats_max: 20,
          why: 'Each beat is one spoken sentence of a measured 6.2 seconds. 16-20 beats lands the finished video in the 1.5-2.5 minute house range.',
          visual_balance: 'At most a third of beats may be "info". Ali must carry the teaching -- consecutive info cards with no character on screen read as flat.',
        },
        ...(redraft ? {
          revision_round: redraft.round,
          reviewer_critique_to_fix: redraft.latest,
          previous_rounds: redraft.history.slice(0, -1),
          instruction: patchMode
            ? [
              'Return a PATCH, not a script. Put one entry in `edits` for each beat you',
              'are changing, with only the fields that change. Beats you do not list are',
              'kept exactly as they are, so you cannot accidentally alter them.',
              'Use `new_beats` only if the reviewer says a MOMENT is missing, and',
              '`removed_ids` only if it calls a beat redundant.',
              'Do not reintroduce a problem an earlier round already named.',
            ].join(' ')
            : 'Fix every point the reviewer listed.',
          previous_beats: previousBeats || undefined,
        } : {}),
      }, null, 2),
      schema: patchMode ? EDIT_SCHEMA : SCHEMA,
      maxTokens: 16000,
      dryRun: opts.dryRun,
      dryRunValue: patchMode
        ? { edits: [] }
        : { title: item.topic, beats: [{ id: '01', mode: 'scene', vo: '(dry run)', art: '(dry run)' }] },
    });

    // Turn a patch back into a full script; a first draft is already one.
    let script;
    if (patchMode) {
      const { beats, touched } = applyEdits(previousBeats, raw);
      script = {
        // The title is not in the patch schema, so it survives a redraft unchanged.
        title: (artifacts.script && artifacts.script.subtopic) || item.topic,
        beats,
      };
      log(`patch applied: ${touched.length} beat(s) changed (${touched.join(', ') || 'none'}), ` +
          `${beats.length - touched.filter((t) => !/^[+-]/.test(t)).length} carried through untouched`);
    } else {
      script = raw;
    }

    // The model writes only the SUBTOPIC. The full learner-facing title follows
    // the house convention "<module> | <module topic> | <subtopic>" and is composed
    // in lib/naming.js -- one place, because the same string reaches the brand
    // bumper, the YouTube title and the review log, and those must not drift.
    const composed = composeTitle(item, script.title);
    if (composed.warning) log(`warning: ${composed.warning}`);
    script.subtopic = script.title;
    script.title = composed.title;
    log(`title: ${script.title}`);

    const dir = videoDir(item.series, item.slug);

    // Same structural check produce runs, applied here so a malformed script is
    // rejected while a retry is still cheap (this stage has maxAttempts 3).
    const { errors, warnings } = validateBeats(script.beats, dir, { strictCanon: true });
    for (const w of warnings) log(`warning: ${w}`);
    if (errors.length) throw new Error(`Malformed script:\n  - ${errors.join('\n  - ')}`);
    const beatsPath = path.join(dir, 'beats.js');

    if (opts.dryRun) {
      log(`dry run -- would write ${script.beats.length} beats to ${beatsPath}`);
    } else {
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(beatsPath, renderBeatsFile(script), 'utf8');
      log(`wrote ${script.beats.length} beats to beats.js`);
    }

    return { ...script, beatsPath, beatCount: script.beats.length };
  },
};
