'use strict';
/**
 * beats-file -- the one function that turns a beats array into beats.js.
 *
 * Lifted out of stages/script.js so the server can rebuild a script from its
 * durable copy without loading the whole script stage (and its model client).
 * There must be exactly one writer: every field the renderer, tts-lesson.js or
 * a sensor reads off a beat has to be emitted here, or it is silently lost on
 * the way to disk -- `cap` and `holdAfter` were each lost that way once.
 */

/** Render the beats array as the beats.js module the pipeline expects. */
function renderBeatsFile(script) {
  const header = [
    '// Generated by the orchestrator spine. One beat = one spoken sentence.',
    `// Title: ${script.title}`,
    '',
    'module.exports = [',
  ];
  const body = script.beats.map((b) => {
    const fields = [
      `    id: ${JSON.stringify(b.id)}`,
      `    mode: ${JSON.stringify(b.mode)}`,
      b.mode === 'checkpoint' ? null : `    vo: ${JSON.stringify(b.vo)}`,
      b.art ? `    art: ${JSON.stringify(b.art)}` : null,
      b.info ? `    info: ${JSON.stringify(b.info)}` : null,
      b.quiz ? `    quiz: ${JSON.stringify(b.quiz)}` : null,
      b.overlay ? `    overlay: ${JSON.stringify(b.overlay)}` : null,
      // Same reason as holdAfter: this function is the ONLY thing that puts a
      // field into beats.js, so a caption the model wrote is lost here unless it
      // is written out -- and the renderer draws captions from beats.js alone.
      b.cap ? `    cap: ${JSON.stringify(b.cap)}` : null,
      // Must be written out, or the quiz beat's thinking pause is silently lost:
      // tts-lesson.js reads holdAfter off the beat in beats.js, and this function
      // is the only thing that puts it there.
      Number(b.holdAfter) > 0 ? `    holdAfter: ${JSON.stringify(Number(b.holdAfter))}` : null,
      b.motion ? `    motion: ${JSON.stringify(b.motion)}` : null,
    ].filter(Boolean).join(',\n');
    return `  {\n${fields},\n  },`;
  });
  return [...header, ...body, '];', ''].join('\n');
}

module.exports = { renderBeatsFile };
