#!/usr/bin/env bash
#
# install-hooks.sh -- put this repo's git hooks where git will actually run them.
#
# WHY THIS EXISTS
# .github/hooks/pre-commit has been in the tree, executable, since the repo was
# set up. Its own header says to copy it into .git/hooks. Nobody had, so
# .git/hooks held nothing but git's stock .sample files and all six of its checks
# fired nowhere. Two of them -- "a test file may not be deleted" and the secret
# scan -- exist in no other place, so they were not merely duplicated by CI.
#
# .git/hooks is not version controlled and cannot be, so a hook in the tree is
# only ever a file until somebody runs something. This is that something, and
# CLAUDE.md points at it so a fresh clone is one command from being guarded.
#
# The pre-push hook runs .claude/scripts/smoke-test.sh. Six separate documents
# already call that script the "Pre-Push Quality Gate" and nothing ran it either.
#
# Idempotent: re-running overwrites with the current version.

set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"
HOOK_DIR="$REPO_ROOT/.git/hooks"

if [ ! -d "$REPO_ROOT/.git" ]; then
  echo "install-hooks: $REPO_ROOT is not a git repository" >&2
  exit 1
fi

mkdir -p "$HOOK_DIR"

# --- pre-commit: the checks that were already written -----------------------
if [ -f "$REPO_ROOT/.github/hooks/pre-commit" ]; then
  cp "$REPO_ROOT/.github/hooks/pre-commit" "$HOOK_DIR/pre-commit"
  chmod +x "$HOOK_DIR/pre-commit"
  echo "  installed pre-commit  (hardcoded prompts, prompts/ and tests/ deletion, pytest, secrets)"
else
  echo "  SKIP pre-commit -- .github/hooks/pre-commit is missing" >&2
fi

# --- pre-push: the gate every doc already claims runs ------------------------
# Written here rather than kept as a file so there is one copy of it, and so the
# reason it exists travels with it.
cat > "$HOOK_DIR/pre-push" <<'HOOK'
#!/usr/bin/env bash
# Generated by scripts/install-hooks.sh -- edit that, not this.
#
# CLAUDE.md, git-workflow/SKILL.md, QA_RATING_SYSTEM.md, DEPLOYMENT_PREREQS.md,
# QA_QUICK_REFERENCE.md and SERVICE_DURABILITY_AND_CONTRACTS.md all call
# smoke-test.sh the "Pre-Push Quality Gate". Until this hook existed it was a
# thing somebody had to remember to type.
set -uo pipefail
REPO_ROOT="$(git rev-parse --show-toplevel)"
GATE="$REPO_ROOT/.claude/scripts/smoke-test.sh"

[ -f "$GATE" ] || { echo "pre-push: $GATE is missing -- not blocking the push" >&2; exit 0; }

echo "pre-push: running the smoke test..."
if bash "$GATE"; then
  exit 0
fi

cat >&2 <<'MSG'

  ❌ Pre-push gate FAILED. The push was not sent.

  Fix what smoke-test.sh reported above, or, if you have read it and are
  certain, push once with --no-verify.
MSG
exit 1
HOOK
chmod +x "$HOOK_DIR/pre-push"
echo "  installed pre-push    (.claude/scripts/smoke-test.sh)"

echo
echo "Hooks installed into .git/hooks. Verify with: ls .git/hooks | grep -v sample"
